### ISSUE TITLE
Update region column in column in queries. 

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-alicloud-compliance#27]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Closing the issue since the fix was made in https://github.com/turbot/steampipe-mod-alicloud-compliance/pull/29
