### ISSUE TITLE
Add missing CIS v1.0.0 controls

### ISSUE THREAD

**Issue by jurajsucik** [turbot/steampipe-mod-alicloud-compliance#46]
**Is your feature request related to a problem? Please describe.**
The following controls are missing:
1.15
5.7
4.6
6.6
7.2
7.3
8.2

**Describe the solution you'd like**
Add the missing controls, at minimum, if programmatic check is not available, mark them as manual verification is required.

**Comment by rajlearner17** [comment]
@jurajsucik Thanks for this issue! 

As discussed herein [slack](https://steampipe.slack.com/archives/C01UECB59A7/p1660055886502809), looking forward to any contributions. We will be happy to help you out. 

We will also check and keep you posted.
