### ISSUE TITLE
Controls should reference their query using `query = ` rather than `sql =`

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-mod-alicloud-compliance#51]
It's simpler in code and readability to reference queries using the query = attribute rather than the sql = attribute.

This occurs throughout the mod, but as a specific example:

https://github.com/turbot/steampipe-mod-alicloud-compliance/blob/178688757489f7b9b351dd6bc614a36872facb80/cis_v100/section_2.sp#L41-L53

Could be changed from:
```
sql           = query.action_trail_enabled.sql
```
to:
```
query         = query.action_trail_enabled
```

**Comment by misraved** [comment]
Closed as a part of https://github.com/turbot/steampipe-mod-alicloud-compliance/pull/52
